app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    pattern:   /login
    defaults:  { _controller: AdminBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout